name: build-manual
run-name: Build manual
on: [push, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-science
      - name: Build the manual
        run: |
          cd $GITHUB_WORKSPACE
          pdflatex manual.tex
          pdflatex manual.tex

      - name: Upload GitHub Pages artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: manual.pdf

  deploy:
    needs: build-manual
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
